-- Family Day Planner (shared password gate, no individual sign-ins)
-- Run this in Supabase SQL editor.

-- 1) Tables
create table if not exists public.settings (
  space_id text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  space_id text not null,
  title text not null,
  status text not null default 'open' check (status in ('open','done')),
  assigned_date date null,
  created_at timestamptz not null default now(),
  completed_at timestamptz null
);

create index if not exists tasks_space_created_idx on public.tasks(space_id, created_at desc);
create index if not exists tasks_space_status_idx on public.tasks(space_id, status);

create table if not exists public.day_plans (
  space_id text not null,
  date date not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(space_id, date)
);

create table if not exists public.day_logs (
  space_id text not null,
  date date not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(space_id, date)
);

-- 2) RLS: allow anon/authenticated to read+write ONLY the default space
alter table public.settings enable row level security;
alter table public.tasks enable row level security;
alter table public.day_plans enable row level security;
alter table public.day_logs enable row level security;

drop policy if exists settings_default_space on public.settings;
create policy settings_default_space on public.settings
  for all to anon, authenticated
  using (space_id = 'default')
  with check (space_id = 'default');

drop policy if exists tasks_default_space on public.tasks;
create policy tasks_default_space on public.tasks
  for all to anon, authenticated
  using (space_id = 'default')
  with check (space_id = 'default');

drop policy if exists plans_default_space on public.day_plans;
create policy plans_default_space on public.day_plans
  for all to anon, authenticated
  using (space_id = 'default')
  with check (space_id = 'default');

drop policy if exists logs_default_space on public.day_logs;
create policy logs_default_space on public.day_logs
  for all to anon, authenticated
  using (space_id = 'default')
  with check (space_id = 'default');

-- 3) Grants (usually already OK, but explicit doesn't hurt)
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.settings to anon, authenticated;
grant select, insert, update, delete on public.tasks to anon, authenticated;
grant select, insert, update, delete on public.day_plans to anon, authenticated;
grant select, insert, update, delete on public.day_logs to anon, authenticated;
